declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';

  export type LucideProps = SVGProps<SVGSVGElement> & {
    size?: number | string;
    absoluteStrokeWidth?: boolean;
    color?: string;
    strokeWidth?: number | string;
    className?: string;
  };

  export type LucideIcon = FC<LucideProps>;

  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowDownUp: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Clock: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Database: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Download: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Gauge: LucideIcon;
  export const Pencil: LucideIcon;
  export const Terminal: LucideIcon;
  export const Trash2: LucideIcon;
  export const FileText: LucideIcon;
  export const Filter: LucideIcon;
  export const Lock: LucideIcon;
  export const Mail: LucideIcon;
  export const Info: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Loader2: LucideIcon;
  export const LogOut: LucideIcon;
  export const Monitor: LucideIcon;
  export const Network: LucideIcon;
  export const Plus: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Save: LucideIcon;
  export const ScrollText: LucideIcon;
  export const Settings: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Ticket: LucideIcon;
  export const Bell: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const GripVertical: LucideIcon;
  export const Hash: LucideIcon;
  export const Menu: LucideIcon;
  export const Package: LucideIcon;
  export const Search: LucideIcon;
  export const Shield: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const User: LucideIcon;
  export const Users: LucideIcon;
  export const Moon: LucideIcon;
  export const Sun: LucideIcon;
  export const Wifi: LucideIcon;
  export const WifiOff: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const Zap: LucideIcon;
}
